apiVersion: v1
entries:
  langgate:
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2025-06-18T14:03:09.041564657Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.4
    - alias: langgate_envoy
      condition: langgate_envoy.enabled
      name: langgate-envoy
      repository: file://../langgate-envoy
      version: 0.1.4
    - alias: langgate_processor
      condition: langgate_processor.enabled
      name: langgate-processor
      repository: file://../langgate-processor
      version: 0.1.4
    - alias: langgate_server
      condition: langgate_server.enabled
      name: langgate-server
      repository: file://../langgate-server
      version: 0.1.4
    description: LangGate AI Gateway - A lightweight, high-performance AI model inference
      gateway
    digest: 8e1072b6fba8ca53c74abcd2e96dac06e8d119cf3ba7e55912e7548a02986b90
    home: https://github.com/Tanantor/langgate
    icon: https://raw.githubusercontent.com/Tanantor/langgate/main/docs/assets/logo.png
    keywords:
    - langgate
    - ai
    - llm
    - gateway
    - proxy
    maintainers:
    - email: saran@tanantor.com
      name: Tanantor
    name: langgate
    sources:
    - https://github.com/Tanantor/langgate
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-0.1.4/langgate-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-04-09T21:27:33.601296612Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.3
    - alias: langgate_envoy
      condition: langgate_envoy.enabled
      name: langgate-envoy
      repository: file://../langgate-envoy
      version: 0.1.3
    - alias: langgate_processor
      condition: langgate_processor.enabled
      name: langgate-processor
      repository: file://../langgate-processor
      version: 0.1.3
    - alias: langgate_server
      condition: langgate_server.enabled
      name: langgate-server
      repository: file://../langgate-server
      version: 0.1.3
    description: LangGate AI Gateway - A lightweight, high-performance AI model inference
      gateway
    digest: 9b9220e2c2be2c6f535255da9bba677e8a8bdc76b96d4009fa41081838a2df66
    home: https://github.com/Tanantor/langgate
    icon: https://raw.githubusercontent.com/Tanantor/langgate/main/docs/assets/logo.png
    keywords:
    - langgate
    - ai
    - llm
    - gateway
    - proxy
    maintainers:
    - email: saran@tanantor.com
      name: Tanantor
    name: langgate
    sources:
    - https://github.com/Tanantor/langgate
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-0.1.3/langgate-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2025-04-09T20:46:29.626963192Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.2
    - alias: langgate_envoy
      condition: langgate_envoy.enabled
      name: langgate-envoy
      repository: file://../langgate-envoy
      version: 0.1.2
    - alias: langgate_processor
      condition: langgate_processor.enabled
      name: langgate-processor
      repository: file://../langgate-processor
      version: 0.1.2
    - alias: langgate_server
      condition: langgate_server.enabled
      name: langgate-server
      repository: file://../langgate-server
      version: 0.1.2
    description: LangGate AI Gateway - A lightweight, high-performance AI model inference
      gateway
    digest: 08577e45d869f4ec2ca7822b9a2ae2b6c8a21fbb1350c0e73df4ba246a1a54f6
    home: https://github.com/Tanantor/langgate
    icon: https://raw.githubusercontent.com/Tanantor/langgate/main/docs/assets/logo.png
    keywords:
    - langgate
    - ai
    - llm
    - gateway
    - proxy
    maintainers:
    - email: saran@tanantor.com
      name: Tanantor
    name: langgate
    sources:
    - https://github.com/Tanantor/langgate
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-0.1.2/langgate-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-04-09T13:31:26.265198287Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.1
    - alias: langgate_envoy
      condition: langgate_envoy.enabled
      name: langgate-envoy
      repository: file://../langgate-envoy
      version: 0.1.1
    - alias: langgate_processor
      condition: langgate_processor.enabled
      name: langgate-processor
      repository: file://../langgate-processor
      version: 0.1.1
    - alias: langgate_server
      condition: langgate_server.enabled
      name: langgate-server
      repository: file://../langgate-server
      version: 0.1.1
    description: LangGate AI Gateway - A lightweight, high-performance AI model inference
      gateway
    digest: d0cd179f1d75eb57ad87dcbe2ed2163ddc1c74a791df8320daa9f049107f3c2b
    home: https://github.com/Tanantor/langgate
    icon: https://raw.githubusercontent.com/Tanantor/langgate/main/docs/assets/logo.png
    keywords:
    - langgate
    - ai
    - llm
    - gateway
    - proxy
    maintainers:
    - email: saran@tanantor.com
      name: Tanantor
    name: langgate
    sources:
    - https://github.com/Tanantor/langgate
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-0.1.1/langgate-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-04-07T23:21:03.495090597Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.0
    - alias: langgate_envoy
      condition: langgate_envoy.enabled
      name: langgate-envoy
      repository: file://../langgate-envoy
      version: 0.1.0
    - alias: langgate_processor
      condition: langgate_processor.enabled
      name: langgate-processor
      repository: file://../langgate-processor
      version: 0.1.0
    - alias: langgate_server
      condition: langgate_server.enabled
      name: langgate-server
      repository: file://../langgate-server
      version: 0.1.0
    description: LangGate AI Gateway - A lightweight, high-performance AI model inference
      gateway
    digest: 8c8062a025e32cc2a8ae05e87af34dd13cd61d2843277242e582d5a99c3944d7
    home: https://github.com/Tanantor/langgate
    icon: https://raw.githubusercontent.com/Tanantor/langgate/main/docs/assets/logo.png
    keywords:
    - langgate
    - ai
    - llm
    - gateway
    - proxy
    maintainers:
    - email: saran@tanantor.com
      name: Tanantor
    name: langgate
    sources:
    - https://github.com/Tanantor/langgate
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-0.1.0/langgate-0.1.0.tgz
    version: 0.1.0
  langgate-envoy:
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2025-06-18T14:03:09.14883124Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.4
    description: Envoy proxy component for LangGate AI Gateway
    digest: 8b7a1249717ec9c9577882fe8b9a5fc1026e57747c75b9a2b8d31003d1bf1f83
    name: langgate-envoy
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-envoy-0.1.4/langgate-envoy-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-04-09T21:27:33.791319979Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.3
    description: Envoy proxy component for LangGate AI Gateway
    digest: dcd97e3d1b81ef1577aeaa1a28c84c38a87e1ad63752fce2cc23113545cfffde
    name: langgate-envoy
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-envoy-0.1.3/langgate-envoy-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2025-04-09T20:46:29.767304034Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.2
    description: Envoy proxy component for LangGate AI Gateway
    digest: d3cec2ded5867bad5009682e0d04eab46844f32bbf2299ce28164a008118c7d8
    name: langgate-envoy
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-envoy-0.1.2/langgate-envoy-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-04-09T13:31:26.48312208Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.1
    description: Envoy proxy component for LangGate AI Gateway
    digest: ee454ae9e17453789f17d022455ec5ad5ba014bb2be93ac1a9e9b85166878027
    name: langgate-envoy
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-envoy-0.1.1/langgate-envoy-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-04-07T23:21:03.649602263Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.0
    description: Envoy proxy component for LangGate AI Gateway
    digest: 649c3166b2c3c33ccd96b9fd1bdb731022a275dcdd507bda8d4c77283dc839bf
    name: langgate-envoy
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-envoy-0.1.0/langgate-envoy-0.1.0.tgz
    version: 0.1.0
  langgate-processor:
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2025-06-18T14:03:09.269946545Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.4
    description: Processor component for LangGate AI Gateway
    digest: c87f0c8b75844b55c99970b6a78772c42f6dd1f16506c210129aa75f7d5ac662
    name: langgate-processor
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-processor-0.1.4/langgate-processor-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-04-09T21:27:33.988034544Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.3
    description: Processor component for LangGate AI Gateway
    digest: fb4ca550ee7c3c1373d9c1a871f596d7db3b2aec41603b6b8a2185888190fc07
    name: langgate-processor
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-processor-0.1.3/langgate-processor-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2025-04-09T20:46:29.907292376Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.2
    description: Processor component for LangGate AI Gateway
    digest: 7199912ca3c43007d0e767712c7edd0f45e17e6d6c0fbe94bcb6e1da8ce333eb
    name: langgate-processor
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-processor-0.1.2/langgate-processor-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-04-09T13:31:26.676351933Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.1
    description: Processor component for LangGate AI Gateway
    digest: c7e526f4e64a7c9271fb7aee2920975f13176493bd0441da09e924190bacfa4d
    name: langgate-processor
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-processor-0.1.1/langgate-processor-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-04-07T23:21:03.783629972Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.0
    description: Processor component for LangGate AI Gateway
    digest: e3876999f5053946b7984ca929e111ef24da1bc6647d58e6ee31fc0cd450731b
    name: langgate-processor
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-processor-0.1.0/langgate-processor-0.1.0.tgz
    version: 0.1.0
  langgate-server:
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2025-06-18T14:03:09.383624501Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.4
    description: Server component for LangGate AI Gateway
    digest: b639e1092218d9bf8f6a23acfa23406ec9314815a8809eae55fc7086f57e280a
    name: langgate-server
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-server-0.1.4/langgate-server-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-04-09T21:27:34.190864327Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.3
    description: Server component for LangGate AI Gateway
    digest: e16831e418fc22070baffab4450f8e96c224031aa9247576da5a04647ac5d7e9
    name: langgate-server
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-server-0.1.3/langgate-server-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2025-04-09T20:46:30.033592824Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.2
    description: Server component for LangGate AI Gateway
    digest: c9f9783d755030c5defdf35d4cd37cb3b6f453a9cbcc38f096fcdbbbe3998ec2
    name: langgate-server
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-server-0.1.2/langgate-server-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2025-04-09T13:31:26.881724555Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.1
    description: Server component for LangGate AI Gateway
    digest: 05234e64dbe25607057bf65279b81cae63b904c0404da33da1b4a4e7432a53b5
    name: langgate-server
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-server-0.1.1/langgate-server-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-04-07T23:21:03.929365523Z"
    dependencies:
    - name: langgate-helpers
      repository: file://../library/langgate-helpers
      version: 0.1.0
    description: Server component for LangGate AI Gateway
    digest: a8f9d7d60e06e05b57326a100bec964dd1fae2a2a3808d782acae4e49d92f923
    name: langgate-server
    type: application
    urls:
    - https://github.com/Tanantor/langgate/releases/download/langgate-server-0.1.0/langgate-server-0.1.0.tgz
    version: 0.1.0
generated: "2025-06-18T14:03:09.383704772Z"
