apiVersion: v2
name: langgate-server
description: Server component for LangGate AI Gateway
type: application
version: 0.0.0
appVersion: "0.0.0"

dependencies:
  - name: langgate-helpers
    repository: file://../library/langgate-helpers
    version: 0.0.0
